on:
  workflow_dispatch:
    inputs:
      environment:
        description: "chose environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy application
        run: echo "deploying the application"
